pipeline {
    agent { label 'laravel-agent' }

    environment {
        TELEGRAM_BOT_TOKEN = credentials('bot-token')
        TELEGRAM_CHAT_ID = '5854378525'
    }

    stages {

        stage('Build Laravel') {
            steps {
                sh '''
                cd my-laravel-app
                composer install --no-dev --optimize-autoloader
                npm install
                npm run build
                '''
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['server-ssh-key']) {
                    sh '''
                    cd ansible
                    export ANSIBLE_HOST_KEY_CHECKING=False
                    ansible-playbook -i inventory.ini playbook.yml
                    '''
                }
            }
        }
    }

    post {
        success {
            sh '''
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="✅ Deploy success (artifact)"
            '''
        }
        failure {
            sh '''
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="❌ Deploy FAILED!"
            '''
        }
    }
}