server {
    listen 80;
    server_name 178.128.93.188;

    root /var/www/178.128.93.188/Chantha_Mengkong/public;
    index index.php;

    location /Chantha_Mengkong {
        try_files $uri $uri/ /Chantha_Mengkong/index.php?$query_string;
    }

    location ~ ^/Chantha_Mengkong/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        include fastcgi_params;
    }
}