server {
    listen 80;
    server_name 178.128.93.188;

    root /var/www/Chantha_Mengkong/public;
    index index.php;

    location /Chantha_Mengkong/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }
}