---
# setup-server.yml
- name: Provision Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install PHP-FPM
      apt:
        name: php-fpm
        state: present

    - name: Ensure Nginx is running and starts on boot
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Push Nginx configuration file to server
      copy:
        src: nginx.conf # Grabs the file from your Jenkins workspace
        dest: /etc/nginx/sites-available/Chantha_Mengkong
        owner: root
        group: root
        mode: '0644'

    - name: Enable the Nginx site (Create Symlink)
      file:
        src: /etc/nginx/sites-available/Chantha_Mengkong
        dest: /etc/nginx/sites-enabled/Chantha_Mengkong
        state: link

    - name: Restart Nginx to apply changes
      systemd:
        name: nginx
        state: restarted