- name: Provision Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx + PHP
      apt:
        name:
          - nginx
          - php-fpm
          - php-cli
          - php-mbstring
          - php-xml
          - php-curl
          - php-zip
          - php-mysql
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
