- name: Provision Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx + PHP
      apt:
        name:
          - nginx
          - php-fpm
          - php-cli
          - php-mbstring
          - php-xml
          - php-curl
          - php-zip
          - php-mysql
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Push Nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/Chantha_Mengkong

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/Chantha_Mengkong
        dest: /etc/nginx/sites-enabled/Chantha_Mengkong
        state: link
        force: yes

    - name: Remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test nginx config
      command: nginx -t

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded